export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_SIGN_OUT_ERROR = 'USER_SIGN_OUT_ERROR';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
